// Manifiesto de pasos de calidad de GlowBook.
// Fuente única de verdad para verify.mjs y para check-ci-parity.mjs.
//
// Campos:
//   id          identificador estable del paso (se usa con --step)
//   tier        'fast' (verify:fast) | 'full' (verify:full, incluye fast)
//   jobs        jobs de CI a los que pertenece (se usan con --job)
//   description texto corto para la tabla de resumen
//   cmd         argv a ejecutar (sin shell); 'node' usa el Node actual
//   needsDb     true si requiere Supabase local levantado (Docker)
//   timeoutMs   límite del paso. Si expira, verify.mjs termina el árbol de
//               procesos y marca el paso como 'timeout' (no espera indefinidamente)
//
// Nunca apunta a staging/producción: solo Supabase local.

/** @type {ReadonlyArray<{id: string, tier: 'fast'|'full', jobs: string[], description: string, cmd: string[], needsDb?: boolean, timeoutMs: number}>} */
export const STEPS = [
  // ---------------------------------------------------------------- fast
  {
    id: "secrets",
    timeoutMs: 120000,
    tier: "fast",
    jobs: ["static"],
    description: "Escaneo de secretos (secretlint) sobre archivos de git",
    cmd: ["node", "scripts/quality/check-secrets.mjs"],
  },
  {
    id: "design-tokens",
    timeoutMs: 120000,
    tier: "fast",
    jobs: ["static"],
    description: "Tokens de diseño (sin colores literales fuera de tokens)",
    cmd: ["node", "scripts/quality/check-design-tokens.mjs"],
  },
  {
    id: "dead-code",
    timeoutMs: 120000,
    tier: "fast",
    jobs: ["static"],
    description: "Código muerto: knip (tests incluidos) y knip --production (solo código de producción)",
    cmd: ["node", "scripts/quality/run-sequence.mjs", "knip", "--then", "knip", "--production"],
  },
  {
    id: "architecture",
    timeoutMs: 120000,
    tier: "fast",
    jobs: ["static"],
    description: "Arquitectura: reglas de capas y dependencias (script + depcruise)",
    cmd: [
      "node",
      "scripts/quality/run-sequence.mjs",
      "node",
      "scripts/check-architecture.mjs",
      "--then",
      "depcruise",
      "--config",
      ".dependency-cruiser.cjs",
      "--ignore-known",
      ".dependency-cruiser-known-violations.json",
      "src",
    ],
  },
  {
    id: "module-size",
    timeoutMs: 120000,
    tier: "fast",
    jobs: ["static"],
    description: "Tamaño de módulos (límite de líneas por archivo)",
    cmd: ["node", "scripts/quality/check-module-size.mjs"],
  },
  {
    id: "ci-parity",
    timeoutMs: 120000,
    tier: "fast",
    jobs: ["static"],
    description: "Paridad entre CI y el manifiesto de pasos",
    cmd: ["node", "scripts/quality/check-ci-parity.mjs"],
  },
  {
    id: "lint",
    timeoutMs: 120000,
    tier: "fast",
    jobs: ["static"],
    description: "ESLint con cero avisos",
    cmd: ["eslint", "--max-warnings", "0"],
  },
  {
    id: "types",
    timeoutMs: 120000,
    tier: "fast",
    jobs: ["static"],
    description: "TypeScript (aplicación y scripts)",
    cmd: [
      "node",
      "scripts/quality/run-sequence.mjs",
      "tsc",
      "--noEmit",
      "--then",
      "tsc",
      "-p",
      "scripts/tsconfig.json",
    ],
  },
  {
    id: "unit",
    timeoutMs: 600000,
    tier: "fast",
    jobs: ["unit"],
    description: "Pruebas unitarias (Vitest, proyecto unit)",
    cmd: ["vitest", "run", "--project", "unit"],
  },
  {
    id: "scripts-tests",
    timeoutMs: 120000,
    tier: "fast",
    jobs: ["unit"],
    description: "Pruebas de scripts (node:test): release, ops, lib y verificador",
    cmd: [
      "node",
      "--test",
      "scripts/lib/target-guard.test.mjs",
      "scripts/ops/synthetic-alert.test.mjs",
      "scripts/ops/synthetic-check.test.mjs",
      "scripts/quality/generate-db-types.test.mjs",
      "scripts/quality/lib-process.test.mjs",
      "scripts/quality/migration-rules.test.mjs",
      "scripts/quality/scripts-tests-list.test.mjs",
      "scripts/release/alert.test.mjs",
      "scripts/release/gate-logic.test.mjs",
      "scripts/release/migrations.test.mjs",
      "scripts/release/smoke-and-url.test.mjs",
    ],
  },

  // ---------------------------------------------------------------- full
  {
    id: "audit-prod",
    timeoutMs: 120000,
    tier: "full",
    jobs: ["static"],
    description: "npm audit de dependencias de producción (cero avisos)",
    cmd: ["node", "scripts/quality/check-audit.mjs", "--prod"],
  },
  {
    id: "audit-all",
    timeoutMs: 120000,
    tier: "full",
    jobs: ["static"],
    description: "npm audit de todas las dependencias (solo excepciones vigentes)",
    cmd: ["node", "scripts/quality/check-audit.mjs", "--all"],
  },
  {
    id: "sbom",
    timeoutMs: 120000,
    tier: "full",
    jobs: ["sbom"],
    description: "SBOM CycloneDX de producción en .quality/sbom.json",
    cmd: ["node", "scripts/quality/write-sbom.mjs"],
  },
  {
    id: "migrations-lint",
    timeoutMs: 600000,
    tier: "full",
    jobs: ["db"],
    description: "Lint de migraciones SQL (squawk y reglas propias)",
    cmd: ["node", "scripts/quality/lint-migrations.mjs"],
  },
  {
    id: "db-reset",
    timeoutMs: 600000,
    tier: "full",
    jobs: ["db"],
    description: "Reconstruye la BD local desde las migraciones",
    cmd: ["supabase", "db", "reset", "--local"],
    needsDb: true,
  },
  {
    id: "db-tests",
    timeoutMs: 600000,
    tier: "full",
    jobs: ["db"],
    description: "Pruebas pgTAP de la BD local",
    cmd: ["supabase", "test", "db"],
    needsDb: true,
  },
  {
    id: "types-drift",
    timeoutMs: 600000,
    tier: "full",
    jobs: ["db"],
    description: "Tipos generados sin deriva respecto a la BD local",
    cmd: ["node", "scripts/quality/check-db-types-drift.mjs"],
    needsDb: true,
  },
  {
    id: "integration",
    timeoutMs: 600000,
    tier: "full",
    jobs: ["db"],
    description: "Pruebas de integración contra Supabase local (no se saltan)",
    cmd: ["vitest", "run", "--project", "integration"],
    needsDb: true,
  },
  {
    id: "coverage",
    timeoutMs: 600000,
    tier: "full",
    jobs: ["db"],
    description: "Cobertura global (trinquete) y del código cambiado",
    cmd: ["node", "scripts/quality/check-coverage.mjs", "--run"],
    needsDb: true,
  },
  {
    id: "build",
    timeoutMs: 600000,
    tier: "full",
    jobs: ["browser", "lighthouse"],
    description: "Build de producción de Next.js",
    cmd: ["next", "build"],
    needsDb: true,
  },
  {
    id: "e2e",
    timeoutMs: 600000,
    tier: "full",
    jobs: ["browser"],
    description: "Flujos críticos E2E con Playwright",
    cmd: ["playwright", "test"],
    needsDb: true,
  },
  {
    id: "lighthouse",
    timeoutMs: 600000,
    tier: "full",
    jobs: ["lighthouse"],
    description: "Lighthouse CI sobre la build local",
    cmd: ["npm", "run", "-s", "lighthouse:ci"],
    needsDb: true,
  },
];
